name: Deploy Web Profile

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Start/Restart Application

        run: |
          pm2 restart web-profile || pm2 start npm --name "web-profile" -- start